GPX-442
gepaplexx/application-day-x-generator pull request #13
Opened 2022-08-30 15:44 UTC by mario-oberwalder

inhibit-rule in template einpflegen

2022-08-31 06:26 UTC, fhochleitner requested changes
Version bitte auch hochziehen vom Day-X-Generator

2022-08-31 06:26 UTC, fhochleitner commented on src/templates/default-alertmanager-config.yaml.tpl
> +  - source_matchers: [alertname = cluster-is-updating]
Alertname bitte (siehe Kommentar in PR im gp-helm-chart-development) beim Namen ändern.

2022-09-01 06:48 UTC, fhochleitner requested changes
bitte noch die Version im "version" File hochziehen.

2022-09-01 06:54 UTC, mario-oberwalder commented
version hochgezogen und gemerged, wie besprochen

2022-09-01 06:57 UTC, merged